### ISSUE TITLE
requests with malformed json body hangs and error is not passed to error handler

### ISSUE THREAD

**Issue by jalkjaer** [dalisoft/nanoexpress#46]
Posting an invalid json body with Content-Type application/json cause request to hang for aprox 10 seconds before the socket is close and the following is written to the console
```
(node:25737) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token a in JSON at position 1
    at JSON.parse (<anonymous>)
    at body (/tmp/nanotest/node_modules/nanoexpress/build/nanoexpress.js:559:21)
    at async /tmp/nanotest/node_modules/nanoexpress/build/nanoexpress.js:1659:11
(node:25737) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
Sample program:
```
const nanoexpress = require('nanoexpress');
const app = nanoexpress();
app.setErrorHandler((err, req, resp) => {
    console.log(err);
    resp.status(500).end(err.message);
});
app.setValidationErrorHandler( (err, req, resp) => {
    console.log(err);
    resp.status(500).end(JSON.stringify(err.errors));
});
app.post('/', (req, resp) => {
    resp.send( "sdfsdfdsf");
});
app.listen(4002).catch((...args) => {
    console.log(args)
});
```
Testing:
```
curl http://localhost:4002/ -H "Content-Type: application/json"-X POST  --data-binary '{a}' 
```

**Comment by dalisoft** [comment]
Hello.

Thanks for using and/or trying out my library. 
Can you confirm please, are you using Pro or Simple version?

**Comment by jalkjaer** [comment]
nanoexpress@1.1.4 - which I assume is the non-pro

**Comment by dalisoft** [comment]
Thanks for confirm. I will soon look at code and will try fix

**Comment by dalisoft** [comment]
@jalkjaer Thanks for reporting issue and this will helps this project always be safe and up-to-date. Good day and wish you all the best!

**Comment by dalisoft** [comment]
This bug allowed attacker execute `async` code with-in web-server and give access to all files contains in server. Bug is now fixed and now project much safer than before
